version: '2'
services:
    cricket-app:
        image: cricket
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cricket-mysql:3306/cricket?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cricket-elasticsearch:9300
        ports:
            - 8080:8080
    cricket-mysql:
        extends:
            file: mysql.yml
            service: cricket-mysql
    cricket-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cricket-elasticsearch
